const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const merge = require("webpack-merge");
const CircularDependencyPlugin = require("circular-dependency-plugin");
const webpack = require("webpack");
const baseConfig = require("./webpack.base");

module.exports = merge(baseConfig, {
  mode: "development",
  devtool: "source-map",
  output: {
    filename: "index.js",
    path: path.resolve(__dirname, "../dist"),
  },
  devServer: { hot: true },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "./src/index.html",
      inlineSource: "runtime~.+\\.js",
      chunksSortMode: "none",
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
    new webpack.EnvironmentPlugin({
      NODE_ENV: "development",
    }),
    new webpack.NamedModulesPlugin(),
  ],
});
